---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  namespace: media
  labels:
    snapshot.home.arpa/enabled: "true"
    app.kubernetes.io/name: prowlarr
    app.kubernetes.io/instance: prowlarr
spec:
  storageClassName: mayastor-triple
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
