---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fpm-override
  namespace: gtd
data:
  99-clear-env.conf: |
    ; Ensure PHP-FPM exposes OS env to PHP
    clear_env = no
    ; Optional: explicitly pass only the vars you need
    ; env[APP_KEY] = ${APP_KEY}
