---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkace
  namespace: gtd
  labels:
    app.kubernetes.io/name: linkace
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: linkace
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: linkace
    spec:
      containers:
        - image: ghcr.io/kovah/linkace:v2.2.0@sha256:baa826d946e04dff901995208aaf040b774ab02dbc89b47a1e016b6e3aabb144
          name: linkace
          ports:
            - containerPort: 80
          # volumeMounts:
          #   - name: linkace-env
          #     mountPath: /app/.env
          #     subPath: env
      restartPolicy: Always
      volumes:
        - name: linkace-env
          configMap:
            name: linkace-env
