---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkace
  namespace: gtd
spec:
  replicas: 1
  selector:
    matchLabels: { app.kubernetes.io/name: linkace }
  strategy:
    type: Recreate
  template:
    metadata:
      labels: { app.kubernetes.io/name: linkace }
    spec:
      volumes:
        - name: la-cache
          emptyDir: {}
        - name: env-file
          emptyDir: {}
      initContainers:
        # Write a real .env from Pod env
        - name: write-env-as-app
          image: ghcr.io/kovah/linkace:v2.2.0
          workingDir: /var/www/html
          command: ["sh", "-lc"]
          args: |
            umask 027 &&
            mkdir -p /work &&
            {
              printf 'APP_KEY=%s\n' "$APP_KEY";
              printf 'DB_CONNECTION=%s\n' "${DB_CONNECTION:-pgsql}";
              printf 'DB_HOST=%s\n' "$DB_HOST";
              printf 'DB_PORT=%s\n' "${DB_PORT:-5432}";
              printf 'DB_DATABASE=%s\n' "$DB_DATABASE";
              printf 'DB_USERNAME=%s\n' "$DB_USERNAME";
              printf 'DB_PASSWORD=%s\n' "$DB_PASSWORD";
            } > /work/.env
          env:
            - name: APP_KEY
              value: ${SECRET_LINKACE_APP_KEY}
            - name: DB_CONNECTION
              value: pgsql
            - name: DB_HOST
              value: buvis-pg-cluster-rw.storage
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: linkace
            - name: DB_USERNAME
              value: linkace
            - name: DB_PASSWORD
              value: ${SECRET_LINKACE_PG_PASSWORD}
          volumeMounts:
            - name: env-file
              mountPath: /work
        - name: artisan-clear
          image: ghcr.io/kovah/linkace:v2.2.0
          workingDir: /var/www/html
          command: ["sh", "-lc"]
          args: >
            php /var/www/html/artisan config:clear &&
            php /var/www/html/artisan cache:clear &&
            php /var/www/html/artisan route:clear || true
          volumeMounts:
            - name: la-cache
              mountPath: /var/www/html/bootstrap/cache
      containers:
        - name: linkace
          image: ghcr.io/kovah/linkace:v2.2.0
          ports:
            - containerPort: 80
          env:
            - name: APP_KEY
              value: ${SECRET_LINKACE_APP_KEY}
            - name: DB_CONNECTION
              value: pgsql
            - name: DB_HOST
              value: buvis-pg-cluster-rw.storage
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: linkace
            - name: DB_USERNAME
              value: linkace
            - name: DB_PASSWORD
              value: ${SECRET_LINKACE_PG_PASSWORD}
          volumeMounts:
            - name: la-cache
              mountPath: /var/www/html/bootstrap/cache
            - name: env-file
              mountPath: /var/www/html/.env
              subPath: .env
