---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: openfaas
  namespace: openfaas
spec:
  dependsOn:
  - name: ingress-nginx
    namespace: kube-tools
  - name: cert-manager
    namespace: kube-tools
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://openfaas.github.io/faas-netes/
      chart: openfaas
      version: 14.2.32
      sourceRef:
        kind: HelmRepository
        name: openfaas
        namespace: flux-system
  values:
    functionNamespace: openfaas-fn
    generateBasicAuth: true
