---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: storage
spec:
  interval: 5m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      chart: minio
      # renovate: registryUrl=https://charts.min.io/
      version: 5.0.14
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  values:
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2025-09-07T16-13-09Z@sha256:14cea493d9a34af32f524e538b8346cf79f3321eff8e708c1e2960462bd8936e
      pullPolicy: IfNotPresent
    mcImage:
      repository: quay.io/minio/mc
      tag: RELEASE.2025-08-13T08-35-41Z@sha256:a7fe349ef4bd8521fb8497f55c6042871b2ae640607cf99d9bede5e9bdf11727
      pullPolicy: IfNotPresent
    mode: standalone
    rootUser: root
    rootPassword: ${SECRET_MINIO_ROOT_PASSWORD}
    users:
      - accessKey: thanos
        secretKey: ${SECRET_MINIO_THANOS_SECRET_KEY}
        policy: readwrite
    persistence:
      enabled: true
      existingClaim: minio-buckets
    ingress:
      enabled: false
    consoleIngress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        authentik.home.arpa/enabled: "true"
      hosts:
        - minio.buvis.net
      tls:
        - secretName: minio-cert
          hosts:
            - minio.buvis.net
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1500Mi
    buckets:
      - name: thanos
        policy: public
        purge: true
        versioning: false
        objectlocking: false
