---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-buckets
  namespace: storage
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
