---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: plugin-barman-cloud
  namespace: flux-system
spec:
  interval: 30m
  ref:
    branch: main
  url: https://github.com/jurim76/plugin-barman-cloud
