---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zettelkasten
  namespace: gtd
spec:
  dependsOn:
    - name: ingress-nginx
      namespace: kube-tools
    - name: cert-manager
      namespace: kube-tools
    - name: authentik
      namespace: security
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://charts.buvis.net
      chart: mkdocs-git-sync
      version: 0.1.10
      sourceRef:
        kind: HelmRepository
        name: buvis
        namespace: flux-system
      interval: 5m
  values:
    config:
      repo: https://gitlab.com/buvis/zettelkasten.git
      credentials: ${SECRET_ZETTELKASTEN_REPO_CREDENTIALS}
      branch: main
      docsDir: zettelkasten
      editUri: https://gitlab.com/buvis/zettelkasten/edit/main/zettelkasten
      updateInterval: 60
      siteName: Bob's Zettelkasten
      siteUrl: https://zkn.buvis.net
      requirements: |
        mkdocs-zettelkasten==0.2.0
        mdx_truly_sane_lists
      theme:
        name: zettelkasten-solarized-light
      extensions:
        - admonition
        - pymdownx.superfences
        - mdx_truly_sane_lists
      plugins:
        - search
        - zettelkasten
      nav:
        - Source: https://gitlab.com/buvis/zettelkasten
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-production
        authentik.home.arpa/enabled: "true"
      hosts:
        - host: zkn.buvis.net
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: zkn-crt
          hosts:
            - zkn.buvis.net
