---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kube-tools
spec:
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://kyverno.github.io/kyverno/
      chart: kyverno
      version: 3.4.1
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  values:
    crds:
      install: true
    replicaCount: 3
    grafana:
      enabled: true
    serviceMonitor:
      enabled: false
      interval: 1m
    backgroundController:
      serviceMonitor:
        enabled: false
        interval: 1m
    cleanupController:
      serviceMonitor:
        enabled: false
        interval: 1m
    reportsController:
      serviceMonitor:
        enabled: false
        interval: 1m
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: kyverno
