---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno-policies
  namespace: flux-system
spec:
  dependsOn:
    - name: kyverno
  interval: 10m0s
  path: ./cluster-home/operations/kube-tools/kyverno/policies
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: Secret
        name: cluster-secret-vars
      - kind: ConfigMap
        name: cluster-config
