# Adapted from example at https://github.com/rancher/system-upgrade-controller/blob/master/examples/k3s-upgrade.yaml
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-server
  namespace: system-upgrade
  labels:
    k3s-upgrade: server
spec:
  concurrency: 1
  # Latest release: https://update.k3s.io/v1-release/channels/stable
  version: v1.22.6+k3s1
  nodeSelector:
    matchExpressions:
    - key: plan.upgrade.cattle.io/k3s-server
      operator: Exists
  tolerations:
  - effect: NoSchedule
    operator: Exists
  serviceAccountName: system-upgrade
  cordon: true
  upgrade:
    image: rancher/k3s-upgrade
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-agent
  namespace: system-upgrade
  labels:
    k3s-upgrade: agent
spec:
  concurrency: 1
  # Latest release: https://update.k3s.io/v1-release/channels/stable¬
  version: v1.22.6+k3s1
  nodeSelector:
    matchExpressions:
    - key: plan.upgrade.cattle.io/k3s-agent
      operator: Exists
  serviceAccountName: system-upgrade
  prepare:
    image: rancher/k3s-upgrade
    args: ["prepare", "k3s-server"]
  drain:
    force: true
    skipWaitForDeleteTimeout: 1200
  upgrade:
    image: rancher/k3s-upgrade
