---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  dependsOn:
    - name: ingress-nginx
      namespace: kube-tools
    - name: cert-manager
      namespace: kube-tools
    - name: openebs
      namespace: storage
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.7.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups:
          - 44
          - 109
          - 65539
    controllers:
      jellyfin:
        containers:
          app:
            image:
              repository: jellyfin/jellyfin
              tag: 10.8.13-1
            env:
              JELLYFIN_CACHE_DIR: /config/cache
              DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
            resources:
              requests:
                cpu: 100m
                memory: 4282M
              limits:
                memory: 12G
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-data
      media:
        enabled: true
        existingClaim: nas-media-videos
        globalMounts:
          - path: /media/videos
      transcode:
        enabled: true
        type: emptyDir
    service:
      app:
        controller: jellyfin
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: ${SVC_IP_JELLYFIN}
        ports:
          http:
            port: 8096
    ingress:
      app:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &hostName jellyfin.buvis.net
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *hostName
            secretName: jellyfin-crt
