---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kopia-ui
  namespace: storage
spec:
  dependsOn:
    - name: ingress-nginx
      namespace: kube-tools
    - name: cert-manager
      namespace: kube-tools
    - name: authentik
      namespace: security
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.7.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    defaultPodOptions:
      securityContext:
        supplementalGroups:
          - 100
    initContainers:
      wait-for-repo:
        image: docker.io/kopia/kopia:20240412.0.225911@sha256:71f87ac0abe4c34808016394635b45eec63a5a934f0baab266516e93ca40fb3e
        command:
          - /bin/bash
          - -c
          - |-
            until [ -f /snapshots/kopia.repository.f ]; do
                printf "\e[1;32m%-6s\e[m\n" "Waiting for the Kopia repo to become ready ..."
                sleep 1
            done
        volumeMounts:
          - name: snapshots
            mountPath: /snapshots
    controllers:
      kopia:
        containers:
          app:
            image:
              repository: docker.io/kopia/kopia
              tag: 20240412.0.225911@sha256:71f87ac0abe4c34808016394635b45eec63a5a934f0baab266516e93ca40fb3e
            env:
              KOPIA_PASSWORD: "none"
            command: kopia
            args:
              - server
              - start
              - --insecure
              - --address
              - 0.0.0.0:80
              - --metrics-listen-addr
              - 0.0.0.0:8080
              - --without-password
              - --log-level
              - debug
    service:
      app:
        controller: kopia
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: ${SVC_IP_KOPIA}
        ports:
          http:
            port: 80
          metrics:
            enabled: true
            port: 8080
    ingress:
      app:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          authentik.home.arpa/enabled: "true"
        hosts:
          - host: &hostName kopia.buvis.net
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *hostName
            secretName: kopia-crt
    persistence:
      config:
        enabled: true
        type: configMap
        name: kopia-ui-config
        globalMounts:
          - path: /config/repository.config
            readOnly: true
            subPath: repository.config
      snapshots:
        enabled: true
        type: nfs
        server: ${FAST_NAS_SERVER_IP}
        path: ${FAST_NAS_PATH_PV}/storage/kopia/snapshots
        globalMounts:
          - path: /snapshots
