---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kopia-jobs
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster-home/operations/storage/kopia/jobs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: Secret
        name: cluster-secret-vars
      - kind: ConfigMap
        name: cluster-config
