---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  dependsOn:
  - name: ingress-nginx
    namespace: kube-tools
  - name: cert-manager
    namespace: kube-tools
  - name: authentik
    namespace: security
  - name: vpn-gateway
    namespace: vpn
  - name: openebs
    namespace: storage
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/onedr0p/radarr-develop
      tag: 5.2.3.8303@sha256:7794a25df2cd26f35e326640510c50982fe2f16ef41666530cdb06db21d3de5d
    env:
      RADARR__APPLICATION_URL: https://radarr.buvis.net
      RADARR__API_KEY: ${SECRET_RADARR_API_KEY}
    podAnnotations:
      setVPNGateway: "true"
    persistence:
      config:
        enabled: true
        existingClaim: radarr-config
      media:
        enabled: true
        existingClaim: nas-media
        mountPath: /media
    service:
      main:
        ports:
          http:
            port: 7878
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-production
          authentik.home.arpa/enabled: "true"
        hosts:
        - host: radarr.buvis.net
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - radarr.buvis.net
          secretName: radarr-crt
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
      - 985
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 2000Mi
