---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: media
  labels:
    snapshot.home.arpa/enabled: "false"
    app.kubernetes.io/name: radarr
    app.kubernetes.io/instance: radarr
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
