- op: add
  path: /cluster/network/cni
  value:
    name: custom
    urls:
      - https://raw.githubusercontent.com/buvis/clusters/main/cluster-office/infrastructure/manifests/deploy-tigera-operator.yaml
      - https://raw.githubusercontent.com/buvis/clusters/main/cluster-office/infrastructure/manifests/install-calico.yaml
- op: replace
  path: /cluster/network/podSubnets
  value:
    - 172.42.0.0/16
- op: replace
  path: /cluster/network/serviceSubnets
  value:
    - 172.44.0.0/16
- op: replace
  path: /machine/install/disk
  value: /dev/mmcblk0
- op: replace
  path: /machine/install/wipe
  value: true
- op: add
  path: /machine/time
  value:
    disabled: false
    servers:
      - 'time.cloudflare.com'
      - 'time.google.com'
      - 'pool.ntp.org'
    bootTimeout: 2m0s
