---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyseerr
  namespace: media
spec:
  dependsOn:
    - name: ingress-nginx
      namespace: kube-tools
    - name: cert-manager
      namespace: kube-tools
    - name: authentik
      namespace: security
    - name: openebs
      namespace: storage
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
    controllers:
      jellyseerr:
        containers:
          app:
            image:
              repository: docker.io/fallenbagel/jellyseerr
              tag: 2.3.0
            env:
              LOG_LEVEL: debug
            resources:
              requests:
                cpu: 15m
                memory: 352Mi
              limits:
                memory: 500Mi
    persistence:
      config:
        enabled: true
        existingClaim: jellyseerr-config
        globalMounts:
          - path: /app/config
    service:
      app:
        controller: jellyseerr
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: ${SVC_IP_JELLYSEERR}
        ports:
          http:
            port: 5055
    ingress:
      app:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          authentik.home.arpa/enabled: "true"
        hosts:
          - host: &hostName requests.buvis.net
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *hostName
            secretName: requests-crt
