apiVersion: v1
kind: Secret
metadata:
    name: windmill-secrets
    namespace: windmill
type: Opaque
stringData:
    url: ENC[AES256_GCM,data:ybcHFYJXGMhIPl1fk9CVsRRVYhMztrwIK6V2vLd7sLNxUkqAGHwk8EMCXU+MD2WZaR2cXUmAmeg2Qc1LWs5eLnzGtNQ1IWG687+NMcOrfJTNsiOyKhVtbxUSTxjf0jCkaNdvUxOmWBWfl0tnN2HBuX9FIkU=,iv:rxlgXgyyr5zi3AVCmcYJyORg9EcWxyav4jIc6wgEFVA=,tag:Yft3XkDna49sfTCht++eYw==,type:str]
    smtp-password: ENC[AES256_GCM,data:O17pl9VY4fbb60l5zgPMpw==,iv:4OqUb3HPkJThyAJqPz/fNvmrUgSPGAhfpFruDkaoYzg=,tag:mC4f7lwg2zS9dcKtAJ3+cg==,type:str]
sops:
    lastmodified: "2026-04-26T12:35:35Z"
    mac: ENC[AES256_GCM,data:uR34lOb0PUmaSrARM8Wb9Nxo8UqYRO1cxldzn2lOJtr0hHFXcjlk4V1UE4d7x/+h3iyqTwch+rM/3XlCOk3TI6tawGhQVXxbooquS1TLzMn7Yl1oiqHgI+E/lapxrLptVevNB6f+ZrGCAAHwzRPPO4Inmj550qQoawmG6ZGCwtA=,iv:mRFBPd8SJFkssuv0E31dFJHfH1Qz3C507ag5RWgrfkk=,tag:8NKj1+DdMC27tZVoS90COA==,type:str]
    pgp:
        - created_at: "2026-04-26T11:37:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+NcdVBF6rzaARAAlrc4IPI0SrIHEfHhDBR6frFL6MIxm/aMMDUhYcFp2iG2
            QplhyTHLlrSlfLJ9gcqqfyaHOiQlFXDbZuFSepIY0Zq5acREywKgceLOHnunvXPr
            DuNUWKVVDAF9tdKdCOtFjrYIjDY2K0Y7is08p/2PgjOjAh4znaQZDk5PBoELZlY9
            zyS1YVpV8TxULVB0Dg9UDMIG1qtovL6TkQd0h7xQ4IeWQmWLQRU/yUQvXOZNKBl/
            w1zqIRiuei08sZEvAMAForld2I55ZbmdkJebeycfmhzWr5xwvDx/C2+DvgQv4MyU
            CZfodbLPk9em9B3ChzwnzwIRsF0HsK2BPFfDmsfIKufQwz3T6LWRIQTTQ4C/C2xT
            lO6V1xWfZSTH3J9QHVM70M6/rh4OfzRw5LvS2nOph7Ay5PeHDSpZjUGncoauyRe/
            qe6tdoxsxKMliiTg+GZIVggx0IX9G9Xx8u5GLIRjhFZvAXdCHkvPtXmFW7vbwhfO
            aCQpgykxqHPZEnQe4TGB5CWUn2nArwNE8uT3ARXcKSwlTNtFbIrJPZMlM3OLF2xs
            HIX8ZpmglK+yB0+9z7TUZEK5maA/Lj86fxw5c9O42vwgyTr7XjX25rxCFWRwc3vl
            gF1Z0jJQJ13R0Jhqt61S9edLXCB4n0e0rZIwcBvHhzUemfiFPLj3O0tLVmNYMB/U
            aAEJAhCyAvaDV2B/vNdYgvf+h8uRmyX7y1UdqpuKQ5RC8cfBxrxXs5+DpvoNCKtN
            FCtzsF9SOw5Z8GcyGX0Uyv1NFETwwPQgkHLk7gozHIIgFRw3cnC7j6KjSBI6tEj7
            g89sHhnxJ4UO
            =99Ig
            -----END PGP MESSAGE-----
          fp: 8E6938876331A62A4B7D5580053DA8FFF394EAD6
    encrypted_regex: ^(data|stringData|caBundle)$
    version: 3.12.2
