---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: authentik
  namespace: storage
spec:
  cluster:
    name: buvis-pg-cluster
  name: authentik
  owner: authentik
  extensions:
    - name: pg_trgm
    - name: citext
