---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: buvis-pg-cluster
  namespace: storage
  annotations:
    longhorn.io/number-of-replicas: "3"
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5@sha256:b1deeed2aa998b2f381e39c5cadb9ec06127708c8bd62965743af19abf21628f
  storage:
    pvcTemplate:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: longhorn
      volumeMode: Filesystem
  postgresql:
    parameters:
      archive_timeout: "30min"  # Reduce WAL generation on idle database (default was 5min)
      wal_keep_size: "128MB"    # Keep less WAL for replicas (down from 512MB)
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    enabled: true
    isWALArchiver: true
    parameters:
      barmanObjectName: buvis-pg-backup
  managed:
    roles:
    - name: authentik
      login: true
      superuser: false
      createdb: false
      passwordSecret:
        name: authentik-db-owner
    - name: linkace
      login: true
      superuser: false
      createdb: false
      passwordSecret:
        name: linkace-db-owner
    services:
      additional:
      - selectorType: rw
        serviceTemplate:
          metadata:
            name: buvis-pg-cluster-rw-lb
          spec:
            type: LoadBalancer
            loadBalancerIP: ${SVC_IP_CNPG_RW}
            externalTrafficPolicy: Cluster
