---
apiVersion: v1
kind: Secret
metadata:
  name: windmill-db-owner
  namespace: storage
type: kubernetes.io/basic-auth
stringData:
  username: windmill
  password: ${SECRET_WINDMILL_PG_PASSWORD}
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: windmill
  namespace: storage
spec:
  cluster:
    name: buvis-pg-cluster
  name: windmill
  owner: windmill
  extensions:
    - name: pg_trgm
    - name: citext
