---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-config
  namespace: media
  labels:
    snapshot.home.arpa/enabled: "true"
    app.kubernetes.io/name: tdarr
    app.kubernetes.io/instance: tdarr
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
# Removed: tdarr-cache now uses emptyDir storage to avoid 3x replication overhead (was 100Gi -> 300Gi disk usage)
# The cache is temporary transcoding data that doesn't need persistence or replication
