---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: baikal-db
  namespace: gtd
spec:
  dependsOn:
    - name: longhorn
      namespace: storage
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: mariadb
      version: 22.0.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    auth:
      database: baikal
      username: baikal
      password: ${SECRET_BAIKAL_DB_PASSWORD}
      rootPassword: ${SECRET_BAIKAL_DB_ROOTPASSWORD}
    primary:
      persistence:
        enabled: true
        existingClaim: baikal-db
