---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baikal-db
  namespace: gtd
  labels:
    snapshot.home.arpa/enabled: "true"
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: baikal-db
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
