---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  dependsOn:
    - name: ingress-nginx
      namespace: kube-tools
    - name: cert-manager
      namespace: kube-tools
    - name: kyverno
      namespace: kube-tools
    - name: openebs
      namespace: storage
  interval: 5m
  install:
    timeout: 45m
    remediation:
      retries: 5
  upgrade:
    timeout: 25m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://charts.goauthentik.io
      chart: authentik
      version: 2025.6.3
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  values:
    kubernetesIntegration: true
    server:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - auth.buvis.net
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        tls:
          - secretName: authentik-https-cert
            hosts:
              - auth.buvis.net
    postgresql:
      enabled: true
      primary:
        persistence:
          existingClaim: authentik-db
      auth:
        password: ${SECRET_AUTHENTIK_DB_PASSWORD}
      image:
        registry: docker.io
        repository: bitnami/postgresql
        tag: 17.5.0
    redis:
      enabled: true
      commonConfiguration: |-
        appendonly no
        save ""
      global:
        defaultStorageClass: mayastor-triple
      persistence:
        enabled: false
      redis:
        useAOFPersistence: "no"
    authentik:
      secret_key: ${SECRET_AUTHENTIK_SECRET_KEY}
      postgresql:
        name: authentik
        user: authentik
        password: ${SECRET_AUTHENTIK_DB_PASSWORD}
    global:
      addPrometheusAnnotations: true
