---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  dependsOn:
  - name: ingress-nginx
    namespace: kube-tools
  - name: cert-manager
    namespace: kube-tools
  interval: 5m
  install:
    timeout: 25m
    remediation:
      retries: 5
  upgrade:
    timeout: 25m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://charts.goauthentik.io
      chart: authentik
      version: 2023.10.5
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  values:
    replicas: 2
    kubernetesIntegration: true
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
      - host: auth.buvis.net
        paths:
        - path: /
          pathType: Prefix
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      tls:
      - secretName: authentik-https-cert
        hosts:
        - auth.buvis.net
    postgresql:
      enabled: true
      persistence:
        existingClaim: authentik-db
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      postgresqlMaxConnections: 500
      postgresqlPassword: ${SECRET_AUTHENTIK_DB_PASSWORD}
    redis:
      enabled: true
      architecture: standalone
      global:
        storageClass: openebs-jiva-csi-default
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
    prometheus:
      serviceMonitor:
        create: true
    authentik:
      secret_key: ${SECRET_AUTHENTIK_SECRET_KEY}
      postgresql:
        name: authentik
        user: authentik
        password: ${SECRET_AUTHENTIK_DB_PASSWORD}
