---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  dependsOn:
    - name: ingress-nginx
      namespace: kube-tools
    - name: cert-manager
      namespace: kube-tools
  interval: 5m
  install:
    timeout: 25m
    remediation:
      retries: 5
  upgrade:
    timeout: 25m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://charts.goauthentik.io
      chart: authentik
      version: 2025.2.1
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  values:
    kubernetesIntegration: true
    server:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - auth.buvis.net
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        tls:
          - secretName: authentik-https-cert
            hosts:
              - auth.buvis.net
    postgresql:
      enabled: true
      primary:
        persistence:
          existingClaim: authentik-db
      auth:
        password: ${SECRET_AUTHENTIK_DB_PASSWORD}
    redis:
      enabled: true
      architecture: standalone
      global:
        storageClass: openebs-jiva-csi-default
    authentik:
      secret_key: ${SECRET_AUTHENTIK_SECRET_KEY}
      postgresql:
        name: authentik
        user: authentik
        password: ${SECRET_AUTHENTIK_DB_PASSWORD}
    global:
      addPrometheusAnnotations: true
