---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  dependsOn:
    - name: ingress-nginx
      namespace: kube-tools
    - name: cert-manager
      namespace: kube-tools
    - name: kyverno
      namespace: kube-tools
    - name: longhorn
      namespace: storage
  interval: 5m
  install:
    timeout: 45m
    remediation:
      retries: 5
  upgrade:
    timeout: 25m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://charts.goauthentik.io
      chart: authentik
      version: 2025.10.2
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  values:
    kubernetesIntegration: true
    server:
      resources:
        requests:
          cpu: 150m
          memory: 512Mi
        limits:
          memory: 1Gi
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - auth.buvis.net
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        tls:
          - secretName: authentik-https-cert
            hosts:
              - auth.buvis.net
    postgresql:
      enabled: false
    redis:
      enabled: true
      commonConfiguration: |-
        appendonly no
        save ""
      global:
        defaultStorageClass: longhorn
      persistence:
        enabled: false
      redis:
        useAOFPersistence: "no"
    authentik:
      secret_key: ${SECRET_AUTHENTIK_SECRET_KEY}
      postgresql:
        host: buvis-pg-cluster-rw.storage.svc.cluster.local
        port: 5432
        name: authentik
        user: authentik
        password: ${SECRET_AUTHENTIK_DB_PASSWORD}
        sslmode: disable
    global:
      addPrometheusAnnotations: true
