---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-db
  namespace: security
  labels:
    snapshot.home.arpa/enabled: "true"
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: authentik
spec:
  storageClassName: mayastor-triple
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
