---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ntfy
  namespace: smarthome
spec:
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  dependsOn:
  - name: ingress-nginx
    namespace: kube-tools
  - name: cert-manager
    namespace: kube-tools
  - name: longhorn
    namespace: storage
  - name: authentik
    namespace: security
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      ntfy:
        containers:
          app:
            image:
              repository: binwiederhier/ntfy
              tag: v2.17@sha256:4768ca4ed07bf5ba0331f333bfccc541ba1594ed7fa5a7b0245763a581809344
            resources:
              requests:
                cpu: 20m
                memory: 64Mi
              limits:
                memory: 256Mi
            env:
              NTFY_AUTH_DEFAULT_ACCESS: deny-all
              NTFY_AUTH_FILE: /var/lib/ntfy/user.db
              NTFY_UPSTREAM_BASE_URL: "https://ntfy.sh"
              NTFY_BASE_URL: "https://ntfy.buvis.net"
            args:
            - serve
    persistence:
      config:
        enabled: true
        existingClaim: ntfy-config
        globalMounts:
        - path: /etc/ntfy
      db:
        enabled: true
        existingClaim: ntfy-db
        globalMounts:
        - path: /var/lib/ntfy
      cache:
        enabled: true
        existingClaim: ntfy-cache
        globalMounts:
        - path: /var/cache/ntfy
    service:
      app:
        controller: ntfy
        ports:
          http:
            port: 80
    ingress:
      app:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
        - host: &hostName ntfy.buvis.net
          paths:
          - path: /
            service:
              identifier: app
              port: http
        tls:
        - hosts:
          - *hostName
          secretName: ntfy-crt
