---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system-dependencies
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster-home/operations/flux-system/dependencies
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
