---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include manifests
    !/**/*.yaml
    # exclude manually applied manifests
    /operations/storage/cnpg/adhoc-backup.yaml
