---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: monica
  namespace: gtd
spec:
  dependsOn:
  - name: ingress-nginx
    namespace: kube-tools
  - name: cert-manager
    namespace: kube-tools
  - name: openebs
    namespace: storage
  - name: monica-db
    namespace: gtd
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: monica
              tag: 4.0.0-apache
            env:
              APP_ENV: production
              APP_KEY: ${SECRET_MONICA_APP_KEY}
              APP_URL: https://crm.buvis.net
              APP_TRUSTED_PROXIES: "*"
              DB_DATABASE: monica
              DB_HOST: monica-db-mariadb
              DB_PASSWORD: ${SECRET_MONICA_DB_PASSWORD}
              DB_USERNAME: monica
              DEFAULT_MAX_UPLOAD_SIZE: 2000
              DEFAULT_MAX_STORAGE_SIZE: 2048
    service:
      main:
        enabled: true
        ports:
          http:
            port: 80
    persistence:
      config:
        enabled: true
        existingClaim: monica-config
      storage:
        enabled: true
        existingClaim: monica-storage
        globalMounts:
        - path: /var/www/html/storage
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/server-snippet: |-
            location ~ /\.well-known/(?:carddav|caldav) {
              return 301 https://$host/dav;
            }
        hosts:
        - host: crm.buvis.net
          paths:
          - path: /
            pathType: Prefix
            service:
              name: main
              port: http
        tls:
        - hosts:
          - crm.buvis.net
          secretName: monica-crt
