.PHONY: update-flux

update-flux:
	flux bootstrap github \
        --owner=buvis-net \
        --repository=clusters \
        --path=./production/operations \
        --branch=main \
        --personal
