---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-plugin-barman-cloud
  namespace: flux-system
spec:
  interval: 5m
  path: ./cluster-home/operations/storage/cnpg-plugin-barman-cloud
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cnpg
      namespace: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: Secret
        name: cluster-secret-vars
