---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dependencies
  namespace: flux-system
resources:
  - longhorn.yaml
  - cnpg.yaml
  - cnpg-plugin-barman-cloud.yaml
