---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-operator-crds
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: prometheus-operator-crds
      version: 21.0.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    crds:
      servicemonitors:
        enabled: true
      prometheusrules:
        enabled: true
      podmonitors:
        enabled: true
