---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: media
  labels:
    snapshot.home.arpa/enabled: "true"
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: qbittorrent
spec:
  storageClassName: mayastor-triple
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
