---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbrr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: qbittorrent
      namespace: media
  values:
    controllers:
      qbrr:
        containers:
          app:
            image:
              repository: ghcr.io/buroa/qbrr
              tag: 0.1.1@sha256:fe4a1d100ba896999253a5122d9c77cc4920779d618c23f765458cb6ec7383ca
            env:
              TZ: Europe/Berlin
              QBITTORRENT_HOST: http://qbittorrent.media:8080
              QBITTORRENT_USERNAME: ${SECRET_QB_USERNAME}
              QBITTORRENT_PASSWORD: ${SECRET_QB_PASSWORD}
              LOG_LEVEL: info
            resources:
              requests:
                memory: 250Mi
                cpu: 25m
              limits:
                memory: 500Mi
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
