---
apiVersion: v1
kind: Secret
metadata:
  name: tqm-config
  namespace: media
stringData:
  config.yaml: |
    clients:
      qbittorrent:
        enabled: true
        type: qbittorrent
        filter: default
        url: http://qbittorrent.media:8080
        user: ${SECRET_QB_USERNAME}
        password: ${SECRET_QB_PASSWORD}

    filters:
      default:
        tag:
          # Tag unregistered torrents
          - name: unregistered
            update:
              - IsUnregistered()

          # Tag expired torrents (7+ days old)
          - name: expired
            update:
              - AddedDays > 7

          # Tag inactive torrents (30+ days without activity)
          - name: inactive
            update:
              - LastActivityDays > 30

          # Tag torrents with tracker errors
          - name: tracker-error
            update:
              - IsTrackerDown()

        # Remove torrents with specific tags, but exclude certain categories
        clean:
          # Remove unregistered torrents after reasonable seeding
          - Category not in ["manual", "music", "music.import", "overlord"] && Label == "unregistered" && (Ratio >= 1.0 || SeedingDays >= 3)

          # Remove expired torrents after good ratio or long seeding time
          - Category not in ["manual", "music", "music.import", "overlord"] && Label == "expired" && (Ratio >= 2.0 || SeedingDays >= 14)

          # Remove inactive torrents after very long seeding
          - Category not in ["manual", "music", "music.import", "overlord"] && Label == "inactive" && SeedingDays >= 30

    orphan:
      # Directories to scan for orphaned files
      directories:
        - /downloads

      # Patterns to exclude from orphan cleanup
      exclude_patterns:
        - "*_unpackerred*"
        - "*/manual/*"
        - "*/music.import/*"

      # Grace period before removing orphans
      grace_period: 10m

      # Remove empty directories
      remove_empty_dirs: true
