---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mopidy-data
  namespace: radio
  labels:
    snapshot.home.arpa/enabled: "true"
    app.kubernetes.io/name: mopidy
    app.kubernetes.io/instance: mopidy
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
