---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: kube-tools
spec:
  dependsOn:
    - name: prometheus-operator-crds
      namespace: monitoring
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 4.13.3
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      allowSnippetAnnotations: true
      hostNetwork: false
      config:
        annotations-risk-level: Critical
        strict-validate-path-type: false
      ingressClassResource:
        default: true
      service:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: ${SVC_IP_INGRESS}
      replicaCount: 3
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: kube-tools
          namespaceSelector:
            any: true
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - ingress-nginx
                topologyKey: kubernetes.io/hostname
