---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkace-db
  namespace: gtd
  labels:
    snapshot.home.arpa/enabled: "true"
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: linkace-db
spec:
  storageClassName: mayastor-triple
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
