---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: barman-cloud
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: .
      sourceRef:
        kind: GitRepository
        name: plugin-barman-cloud
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/cloudnative-pg/plugin-barman-cloud
      tag: "v0.6.0"
      pullPolicy: IfNotPresent
    serviceAccount:
      name: plugin-barman-cloud
