#!/usr/bin/env sh
buvisctl restore -n security authentik-db
buvisctl restore -n gtd linkace-db
buvisctl restore -n gtd baikal-db
buvisctl restore -n gtd baikal-config
buvisctl restore -n gtd baikal-data
buvisctl restore -n smarthome hass-config
buvisctl restore -n radio mopidy-data
buvisctl restore -n media prowlarr-config
buvisctl restore -n media qbittorrent-config
buvisctl restore -n media sabnzbd-config
buvisctl restore -n media bazarr-config
buvisctl restore -n media lidarr-config
buvisctl restore -n media radarr-config
buvisctl restore -n media radarr-cz-config
buvisctl restore -n media sonarr-config
buvisctl restore -n media sonarr-cz-config
buvisctl restore -n media jellyseerr-config
buvisctl restore -n media tdarr-data
buvisctl restore -n media tdarr-config
