---
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: cnpg-adhoc-backup
  namespace: storage
spec:
  cluster:
    name: buvis-pg-cluster
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
