---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: authentik
  namespace: storage
spec:
  cluster: buvis-pg-cluster
  name: authentik
  owner: authentik
  extensions:
    enabled:
      - name: pg_trgm
      - name: citext
