---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: buvis-pg-cluster
  namespace: storage
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5@sha256:b1deeed2aa998b2f381e39c5cadb9ec06127708c8bd62965743af19abf21628f
  storage:
    size: 10Gi
  managed:
    roles:
      - name: authentik
        login: true
        superuser: false
        createdb: false
        passwordSecret:
          name: authentik-db-owner
  serviceTemplates:
    - metadata:
        name: rw
      spec:
        type: LoadBalancer
        loadBalancerIP: 10.11.0.86
        externalTrafficPolicy: Local
