---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg
  namespace: flux-system
spec:
  dependsOn:
  - name: flux-system-extras
  - name: longhorn
    namespace: flux-system
  interval: 5m
  path: "./cluster-home/operations/storage/cnpg"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
    - kind: Secret
      name: cluster-secret-vars
    - kind: ConfigMap
      name: cluster-config
