---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-databases
  namespace: flux-system
spec:
  dependsOn:
    - name: cnpg-plugin-barman-cloud
  interval: 10m0s
  path: ./cluster-home/operations/storage/cnpg/databases
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: Secret
        name: cluster-secret-vars
      - kind: ConfigMap
        name: cluster-config
