---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudnative-pg
      # renovate: registryUrl=https://cloudnative-pg.github.io/charts
      version: 0.26.0
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
