---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudnative-pg
      # renovate: registryUrl=https://cloudnative-pg.github.io/charts
      version: 0.26.0
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    image:
      repository: ghcr.io/cloudnative-pg/cloudnative-pg
      tag: 1.28.1@sha256:0edcdaefaa83d68822158cf4370d83d185c54db2b6beb7e0848aca16eafa6344
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
