---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudnative-pg
      # renovate: registryUrl=https://cloudnative-pg.github.io/charts
      version: 0.26.0
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  values:
    image:
      repository: ghcr.io/cloudnative-pg/cloudnative-pg
      tag: 1.28.2@sha256:510de37115a75f364e9464e1796352a80c5f4b05a62b5aac5d713e9d7548aa1f
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
