---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cnpg
  namespace: storage
resources:
  - authentik-secret.yaml
  - databases.yaml
  - helmrelease.yaml
  - scheduled-backup.yaml
