---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cnpg-scheduled-backup
  namespace: storage
spec:
  schedule: "30 3 * * *"
  backupOwnerReference: self
  cluster:
    name: buvis-pg-cluster
  immediate: true
