---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: groundhog2k
  namespace: flux-system
spec:
  interval: 10m
  url: https://groundhog2k.github.io/helm-charts/
  timeout: 3m
