---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  interval: 5m
  dependsOn:
  - name: ingress-nginx
    namespace: kube-system
  - name: oauth2-proxy
    namespace: kube-system
  - name: cert-manager
    namespace: kube-system
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.2.4
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      defaultClassReplicaCount: 3
      defaultFsType: ext4
    defaultSettings:
      backupTarget: ${NFS_SERVER_PATH_LONGHORN_BACKUP}
      defaultDataPath: /longhorn
      defaultReplicaCount: 3
      defaultLonghornStaticStorageClass: longhorn
      replicaAutoBalance: best-effort
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
    ingress:
      enabled: true
      ingressClassName: nginx
      host: longhorn.buvis.net
      tls: true
      tlsSecret: longhorn-frontent-crt
      annotations:
        cert-manager.io/cluster-issuer: zerossl
        nginx.ingress.kubernetes.io/auth-url: "https://auth.buvis.net/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://auth.buvis.net/oauth2/start?rd=https%3A%2F%2F$host$request_uri"
