---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapserver
  namespace: radio
spec:
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://charts.buvis.net
      chart: snapserver
      version: 0.2.0
      sourceRef:
        kind: HelmRepository
        name: buvis
        namespace: flux-system
      interval: 5m
  values:
    service:
      main:
        enabled: true
        type: LoadBalancer
        externalIPs:
          - ${SVC_IP_SNAPSERVER}
        externalTrafficPolicy: Local
        ports:
          http:
            port: 80
      audio:
        enabled: true
        type: LoadBalancer
        externalIPs:
          - ${SVC_IP_SNAPSERVER}
        externalTrafficPolicy: Local
        ports:
          audio:
            port: 1704
      control:
        enabled: true
        type: LoadBalancer
        externalIPs:
          - ${SVC_IP_SNAPSERVER}
        externalTrafficPolicy: Local
        ports:
          control:
            port: 1705
      stream1:
        enabled: true
        type: LoadBalancer
        externalIPs:
          - ${SVC_IP_SNAPSERVER}
        externalTrafficPolicy: Local
        ports:
          stream1:
            port: 4955
