---
bgpControlPlane:
  enabled: true
certgen:
  image:
    tag: v0.4.3
    digest: sha256:d63d1cb3ee6db2167cb1ca9e7e31f30b6197846fcf42505d8f59e2f090a42c86
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
ipam:
  mode: kubernetes
k8sServiceHost: localhost
k8sServicePort: 7445
kubeProxyReplacement: true
securityContext:
  capabilities:
    ciliumAgent:
    - CHOWN
    - KILL
    - NET_ADMIN
    - NET_RAW
    - IPC_LOCK
    - SYS_ADMIN
    - SYS_RESOURCE
    - DAC_OVERRIDE
    - FOWNER
    - SETGID
    - SETUID
    cleanCiliumState:
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_RESOURCE
hubble:
  tls:
    auto:
      method: cronJob
upgradeCompatibility: '1.19'
