cluster:
  network:
    cni:
      name: none
    podSubnets:
      - 172.22.0.0/16
    serviceSubnets:
      - 172.24.0.0/16
  proxy:
    disabled: true
machine:
  install:
    wipe: true
    image: factory.talos.dev/metal-installer/decca0d019b92170b9c7101da90f1ec0de7e9841b3d126ac4111743778d8eb1a:v1.12.3
    diskSelector:
      size: <100GB
    extraKernelArgs:
      - amd_pstate=active
  time:
    disabled: false
    servers:
      - "time.cloudflare.com"
      - "time.google.com"
      - "pool.ntp.org"
    bootTimeout: 2m0s
  network:
    searchDomains:
      - svc.cluster.local
      - cluster.local
