- op: add
  path: /cluster/network/cni
  value:
    name: none
- op: add
  path: /cluster/proxy
  value:
    disabled: true
- op: replace
  path: /cluster/network/podSubnets
  value:
    - 172.22.0.0/16
- op: replace
  path: /cluster/network/serviceSubnets
  value:
    - 172.24.0.0/16
- op: replace
  path: /machine/install/wipe
  value: true
- op: replace
  path: /machine/install/image
  value: factory.talos.dev/metal-installer/a7bcadbc1b6d03c0e687be3a5d9789ef7113362a6a1a038653dfd16283a92b6b:v1.10.4
- op: add
  path: /machine/install/diskSelector
  value:
    size: <100GB
- op: add
  path: /machine/time
  value:
    disabled: false
    servers:
      - "time.cloudflare.com"
      - "time.google.com"
      - "pool.ntp.org"
    bootTimeout: 2m0s
