- op: add
  path: /machine/kubelet
  value:
    extraMounts:
      - destination: /var/local
        type: bind
        source: /var/local
        options:
          - bind
          - rshared
          - rw
- op: add
  path: /machine/nodeLabels
  value:
    openebs.io/engine: "mayastor"
- op: add
  path: /machine/sysctls
  value:
    vm.nr_hugepages: "1024"
