- op: add
  path: /machine/disks
  value:
    - device: /dev/sdb
      partitions:
        - mountpoint: /var/lib/longhorn
- op: add
  path: /machine/kernel
  value:
    modules:
      - name: nvme_tcp
      - name: vfio_pci
- op: add
  path: /machine/kubelet
  value:
    extraMounts:
      - destination: /var/local
        type: bind
        source: /var/local
        options:
          - bind
          - rshared
          - rw
- op: add
  path: /machine/kubelet
  value:
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
- op: add
  path: /machine/nodeLabels
  value:
    node.longhorn.io/create-default-disk: true
- op: add
  path: /machine/sysctls
  value:
    vm.nr_hugepages: "1024"
