- op: add
  path: /cluster/network/cni
  value:
    name: none
- op: add
  path: /cluster/proxy
  value:
    disabled: true
- op: replace
  path: /cluster/network/podSubnets
  value:
    - 172.22.0.0/16
- op: replace
  path: /cluster/network/serviceSubnets
  value:
    - 172.24.0.0/16
- op: replace
  path: /machine/install/wipe
  value: true
- op: replace
  path: /machine/install/image
  value: factory.talos.dev/metal-installer/860c33aae2de83e2b2feef30dc06e26551d3a5f402f980ee9cd25c17dd9fc744:v1.10.4
- op: add
  path: /machine/install/diskSelector
  value:
    size: <100GB
- op: add
  path: /machine/time
  value:
    disabled: false
    servers:
      - "time.cloudflare.com"
      - "time.google.com"
      - "pool.ntp.org"
    bootTimeout: 2m0s
- op: add
  path: /machine/install/extraKernelArgs
  value:
    - amd_pstate=active
    - isolcpus=6
    - cpufreq.default_governor=powersave
