---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hass
  namespace: smarthome
spec:
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  dependsOn:
  - name: ingress-nginx
    namespace: kube-tools
  - name: cert-manager
    namespace: kube-tools
  - name: longhorn
    namespace: storage
  - name: authentik
    namespace: security
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      hass:
        containers:
          app:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2026.2.2@sha256:3e2dff545c46e91f4ab2b21597016011d76d0de58bc8eaf51d75e841f337bf88
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 1Gi
          codeserver:
            image:
              repository: codercom/code-server
              tag: 4.109.2@sha256:1b84cd817fe8eb1159323ae9d2f29b3c70c6ccd44958d651a94900cf7f0ff9c4
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 512Mi
            workingDir: "/config"
            args:
            - --auth
            - "none"
            - --user-data-dir
            - "/config/.vscode"
            - --extensions-dir
            - "/config/.vscode"
            - --port
            - "12321"
    persistence:
      config:
        enabled: true
        existingClaim: hass-config
      control:
        enabled: true
        existingClaim: syno-control
    service:
      app:
        controller: hass
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: ${SVC_IP_HASS}
        ports:
          http:
            port: 8123
          coiot:
            port: 5683
          https:
            port: 443
      codeserver:
        type: ClusterIP
        controller: hass
        ports:
          http:
            enabled: true
            port: 12321
            protocol: TCP
    ingress:
      app:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.org/websocket-services: hass
        hosts:
        - host: &hostName hass.buvis.net
          paths:
          - path: /
            service:
              identifier: app
              port: http
        tls:
        - hosts:
          - *hostName
          secretName: hass-crt
      codeserver:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          authentik.home.arpa/enabled: "true"
        hosts:
        - host: &hostNameEditor hass-editor.buvis.net
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: codeserver
              port: http
        tls:
        - hosts:
          - *hostNameEditor
          secretName: hass-editor-crt
