---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hass
  namespace: smarthome
spec:
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  dependsOn:
  - name: ingress-nginx
    namespace: kube-tools
  - name: cert-manager
    namespace: kube-tools
  - name: openebs
    namespace: storage
  - name: authentik
    namespace: security
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2023.12.1
    persistence:
      config:
        enabled: true
        existingClaim: hass-config
    service:
      main:
        type: LoadBalancer
        externalIPs:
        - ${SVC_IP_HASS}
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8123
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.org/websocket-services: hass
        hosts:
        - host: hass.buvis.net
          paths:
          - path: /
            service:
              name: main
              port: http
        tls:
        - hosts:
          - hass.buvis.net
          secretName: hass-crt
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 4.19.1
        workingDir: "/config"
        args:
        - --auth
        - "none"
        - --user-data-dir
        - "/config/.vscode"
        - --extensions-dir
        - "/config/.vscode"
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
            cert-manager.io/cluster-issuer: letsencrypt-production
            authentik.home.arpa/enabled: "true"
          hosts:
          - host: hass-editor.buvis.net
            paths:
            - path: /
              pathType: Prefix
          tls:
          - hosts:
            - hass-editor.buvis.net
            secretName: hass-editor-crt
        volumeMounts:
        - name: config
          mountPath: /config
