---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hass-config
  namespace: smarthome
  annotations:
    longhorn.io/number-of-replicas: "3"
  labels:
    snapshot.home.arpa/enabled: "true"
    app.kubernetes.io/name: hass
    app.kubernetes.io/instance: hass
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: syno-control
spec:
  storageClassName: syno-control
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NFS_SERVER_IP}
    path: ${NFS_SERVER_PATH_CONTROL}
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syno-control
  namespace: smarthome
spec:
  storageClassName: syno-control
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
