---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: openebs
      # renovate: registryUrl=https://openebs.github.io/jiva-operator
      version: 3.3.0
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  values:
    localprovisioner:
      enabled: true
      basePath: "/var/openebs/local"
