---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kopia-sync-to-b2
  namespace: storage
spec:
  schedule: "0 6 * * *"
  suspend: false
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 259200
      template:
        spec:
          automountServiceAccountToken: false
          restartPolicy: OnFailure
          initContainers:
            - name: wait-for-repo
              image: docker.io/kopia/kopia:20240412.0.225911@sha256:71f87ac0abe4c34808016394635b45eec63a5a934f0baab266516e93ca40fb3e
              command:
                - /bin/bash
                - -c
                - |-
                  until [ -f /snapshots/kopia.repository.f ]; do
                      printf "\e[1;32m%-6s\e[m\n" "Awaiting for the Kopia repo to become ready ..."
                      sleep 1
                  done
              volumeMounts:
                - name: snapshots
                  mountPath: /snapshots
          containers:
            - name: maintenance
              image: docker.io/kopia/kopia:20240412.0.225911@sha256:71f87ac0abe4c34808016394635b45eec63a5a934f0baab266516e93ca40fb3e
              env:
                - name: TZ
                  value: ${TIMEZONE}
                - name: KOPIA_CACHE_DIRECTORY
                  value: /snapshots/cache
                - name: KOPIA_LOG_DIR
                  value: /snapshots/logs
                - name: KOPIA_PASSWORD
                  value: ${SECRET_KOPIA_PASSWORD}
                - name: AWS_ACCESS_KEY_ID
                  value: ${SECRET_B2_KOPIA_KEY_ID}
                - name: AWS_SECRET_ACCESS_KEY
                  value: ${SECRET_B2_KOPIA_APPLICATION_KEY}
              command:
                - /bin/bash
                - -c
                - |
                  printf "\e[1;32m%-6s\e[m\n" "[01/03] Connect to repo ..."       && kopia repo connect filesystem --path=/snapshots --override-hostname=cluster --override-username=root
                  printf "\e[1;32m%-6s\e[m\n" "[02/03] Sync repository to B2 ..." && kopia repository sync-to s3 --endpoint="s3.us-west-000.backblazeb2.com" --bucket=backup-buvis-home-kopia --access-key=$AWS_ACCESS_KEY_ID --secret-acces-key=$AWS_SECRET_ACCESS_KEY
                  printf "\e[1;32m%-6s\e[m\n" "[03/03] Disconnect from repo ..."  && kopia repo disconnect
              volumeMounts:
                - name: snapshots
                  mountPath: /snapshots
              securityContext:
                privileged: true
          volumes:
            - name: snapshots
              nfs:
                server: ${FAST_NAS_SERVER_IP}
                path: ${FAST_NAS_PATH_PV}/storage/kopia/snapshots
