---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  dependsOn:
  - name: loki
    namespace: monitoring
  - name: kube-prometheus-stack
    namespace: monitoring
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: promtail
      version: 6.4.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 5m
  values:
    config:
      lokiAddress: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
      snippets:
        extraScrapeConfigs: |
          - job_name: syslog
            syslog:
              listen_address: 0.0.0.0:1514
              label_structured_data: true
              labels:
                job: "syslog"
            relabel_configs:
            - source_labels: ['__syslog_connection_ip_address']
              target_label: 'ip_address'
            - source_labels: ['__syslog_message_severity']
              target_label: 'severity'
            - source_labels: ['__syslog_message_facility']
              target_label: 'facility'
            - source_labels: ['__syslog_message_hostname']
              target_label: 'host'
            - source_labels: ['__syslog_message_app_name']
              target_label: 'app'
            - source_labels: ['__syslog_message_SRC']
              target_label: 'source_ip'
            - source_labels: ['__syslog_message_SPT']
              target_label: 'source_port'
            - source_labels: ['__syslog_message_DPT']
              target_label: 'destination_port'
            - source_labels: ['__syslog_message_DST']
              target_label: 'destination_ip'
    extraPorts:
      syslog:
        name: syslog
        containerPort: 1514
        service:
          type: LoadBalancer
          externalIPs:
          - ${SVC_IP_PROMTAIL}
          externalTrafficPolicy: Local
    serviceMonitor:
      enabled: true
