---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: baikal
  namespace: gtd
spec:
  dependsOn:
  - name: ingress-nginx
    namespace: kube-tools
  - name: cert-manager
    namespace: kube-tools
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      baikal:
        containers:
          app:
            image:
              repository: ckulka/baikal
              tag: 0.10.1-nginx
    service:
      app:
        controller: baikal
        ports:
          http:
            port: 80
    ingress:
      app:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
        - host: &hostName dav.buvis.net
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
        tls:
        - hosts:
          - *hostName
          secretName: dav-crt
    persistence:
      config:
        enabled: true
        existingClaim: baikal-config
        globalMounts:
        - path: /var/www/baikal/config
      data:
        enabled: true
        existingClaim: baikal-data
        globalMounts:
        - path: /var/www/baikal/Specific
