---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baikal-config
  namespace: gtd
  labels:
    snapshot.home.arpa/enabled: "true"
    app.kubernetes.io/name: baikal
    app.kubernetes.io/instance: baikal
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baikal-data
  namespace: gtd
  labels:
    snapshot.home.arpa/enabled: "true"
    app.kubernetes.io/name: baikal
    app.kubernetes.io/instance: baikal
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
