---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radicale
  namespace: gtd
spec:
  dependsOn:
    - name: ingress-nginx
      namespace: kube-tools
    - name: cert-manager
      namespace: kube-tools
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      radicale:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: tomsquest/docker-radicale
              tag: 3.5.5.0@sha256:0c26cce308d63b3af01f4a3ea1f66246a23c2ead7c1987d5cc7284073d3719d5
    service:
      app:
        controller: radicale
        ports:
          http:
            port: 5232
    ingress:
      app:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/proxy-body-size: 100M
        hosts:
          - host: &hostName radicale.buvis.net
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *hostName
            secretName: radicale-crt
    persistence:
      auth:
        enabled: true
        type: secret
        name: radicale-users
        globalMounts:
          - path: /config/users
            subPath: users
            readOnly: true
      config:
        enabled: true
        type: configMap
        name: radicale-config
        globalMounts:
          - path: /config/config
            subPath: config.cfg
            readOnly: true
      data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: radicale-data
        globalMounts:
          - path: /data
