---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radicale-data
  namespace: gtd
  labels:
    snapshot.home.arpa/enabled: "true"
    app.kubernetes.io/name: radicale
    app.kubernetes.io/instance: radicale
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
