apiVersion: v1
kind: Secret
metadata:
    name: radicale-users
    namespace: gtd
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:r+mvglZ5Tgf+xAhO/DtPJNZqOKqz4TOHAovKuQrv4RDGpwZAWrJi0tZ+C+NqULnMEmE6pg==,iv:EtB6F2f7KlDNgdUiuCqW88u5oDbrnvCpxxwlgjG02VY=,tag:pZMiQnwkUNja7BEhivv+dA==,type:str]
sops:
    lastmodified: "2025-09-10T08:43:05Z"
    mac: ENC[AES256_GCM,data:ws1KdoX5aJda7IkIevPqMYHW0TsoFUntk8NcIP8TOuYPqN33wa1mGOqBHD3S0k67wA1vCa6tFkYb5zLHelsK5HfMc2of64AJ9Dz1iD1PWdvZtdUhSqtuqXaP9qhAHWIjXpmb0GxE/YcspAFEYTAeXABCgBP8IoWQqWMPw0uP0eo=,iv:rloABXUFE9pvi9iSD0xP2fk+AiGoUp51fgSLxHyKRjA=,tag:O3+OvPEz5nXZkFrwew8q+w==,type:str]
    pgp:
        - created_at: "2025-09-08T18:38:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+NcdVBF6rzaAQ//TVFDV+SJKKAL3jexzulRB94xiRWthluOtEaWdTYJray1
            AY+jSnEt4nBewkU4Oi9myE/dCS86k3/jc92T2WJQz5CJE2NgHG2zyAXrbo8wQaw/
            Y+yZGx0DLTWp7dti1rMF4WlxB06zHmO51LIe+G+poQc4MngHSr8sf6bjvMos6n++
            otYC5ur7Aq1iHtEMuOrbWuVBqw/6Wn3YHMfys+ohtLAkmqlFlhwfNS4ET872c9fj
            MNlAKIkX7OYNAM/ZUNhjpoDRNYgxZWnc4pWOvRnHC1owce9Zqa+5wjYUbsTOXWpU
            RQaS6IRiepE1pW4x3AC/inDXGDKZF2gqKQ+lAAFvfwYVlpHCGGSDpAKwsxOUeFk0
            RrGck47p1xaUAW8U3BpiQk0XonJafiL2aJvkBeCeID/Odbd8CNVu3/YUgaTLdfGe
            owckkRy3qgJZWNQCBg+Sjwh8xLttP2w4+bM2FeTi1uyJOMgBshiaw03oiDNlCQnG
            lNiZPcVMCneWfjtjzMQOk2d4Yo6tcxjY/8tZm0GsEx7u7Fplvjd4uR3jrYBzvhv2
            uHQruHu/NdTsSg+FgGEnULZ/5AU8v5A9cuMdpYTOCwhYcdo8o4Yw8VlRMMfOtsdJ
            RRqBUN/+47BHJdJ6b7MRN//knlIcMJMYCY7sxac5IhLdENU9f9t8eeg9Y0oAmU7U
            aAEJAhA7N0OHoUEH+siR/FiKZIkvJQugMyTeSgdnVdUsehUDQ/6q5VQNRUqxlH95
            fpPFHZFVVwyJPZZ8KWLfvEwwzBwArVQRFDiu1pLtikwugmvph3ZeeJGpU4qIacol
            //rU5MO6nEFs
            =ro9+
            -----END PGP MESSAGE-----
          fp: 8E6938876331A62A4B7D5580053DA8FFF394EAD6
    encrypted_regex: ^(data|stringData|caBundle)$
    version: 3.10.2
